/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module adder(a, b, s, cout);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  input [9:0] a;
  wire [9:0] a;
  input [9:0] b;
  wire [9:0] b;
  output cout;
  wire cout;
  output [9:0] s;
  wire [9:0] s;
  AND2x2_ASAP7_75t_L _18_ (
    .A(a[0]),
    .B(b[0]),
    .Y(_00_)
  );
  MAJx3_ASAP7_75t_L _19_ (
    .A(a[1]),
    .B(b[1]),
    .C(_00_),
    .Y(_01_)
  );
  MAJx3_ASAP7_75t_L _20_ (
    .A(a[2]),
    .B(b[2]),
    .C(_01_),
    .Y(_02_)
  );
  MAJx3_ASAP7_75t_L _21_ (
    .A(a[3]),
    .B(b[3]),
    .C(_02_),
    .Y(_03_)
  );
  MAJx3_ASAP7_75t_L _22_ (
    .A(a[4]),
    .B(b[4]),
    .C(_03_),
    .Y(_04_)
  );
  MAJx3_ASAP7_75t_L _23_ (
    .A(a[5]),
    .B(b[5]),
    .C(_04_),
    .Y(_05_)
  );
  MAJx3_ASAP7_75t_L _24_ (
    .A(a[6]),
    .B(b[6]),
    .C(_05_),
    .Y(_06_)
  );
  MAJx3_ASAP7_75t_L _25_ (
    .A(a[7]),
    .B(b[7]),
    .C(_06_),
    .Y(_07_)
  );
  MAJx3_ASAP7_75t_L _26_ (
    .A(a[8]),
    .B(b[8]),
    .C(_07_),
    .Y(_08_)
  );
  MAJx3_ASAP7_75t_L _27_ (
    .A(a[9]),
    .B(b[9]),
    .C(_08_),
    .Y(cout)
  );
  XOR2x2_ASAP7_75t_L _28_ (
    .A(a[0]),
    .B(b[0]),
    .Y(s[0])
  );
  XNOR2x2_ASAP7_75t_L _29_ (
    .A(a[5]),
    .B(b[5]),
    .Y(_09_)
  );
  XNOR2x2_ASAP7_75t_L _30_ (
    .A(_09_),
    .B(_04_),
    .Y(s[5])
  );
  XNOR2x2_ASAP7_75t_L _31_ (
    .A(a[8]),
    .B(b[8]),
    .Y(_10_)
  );
  XNOR2x2_ASAP7_75t_L _32_ (
    .A(_10_),
    .B(_07_),
    .Y(s[8])
  );
  XNOR2x2_ASAP7_75t_L _33_ (
    .A(a[6]),
    .B(b[6]),
    .Y(_11_)
  );
  XNOR2x2_ASAP7_75t_L _34_ (
    .A(_11_),
    .B(_05_),
    .Y(s[6])
  );
  XNOR2x2_ASAP7_75t_L _35_ (
    .A(a[9]),
    .B(b[9]),
    .Y(_12_)
  );
  XNOR2x2_ASAP7_75t_L _36_ (
    .A(_12_),
    .B(_08_),
    .Y(s[9])
  );
  XNOR2x2_ASAP7_75t_L _37_ (
    .A(a[7]),
    .B(b[7]),
    .Y(_13_)
  );
  XNOR2x2_ASAP7_75t_L _38_ (
    .A(_13_),
    .B(_06_),
    .Y(s[7])
  );
  XNOR2x2_ASAP7_75t_L _39_ (
    .A(a[3]),
    .B(b[3]),
    .Y(_14_)
  );
  XNOR2x2_ASAP7_75t_L _40_ (
    .A(_14_),
    .B(_02_),
    .Y(s[3])
  );
  XNOR2x2_ASAP7_75t_L _41_ (
    .A(a[4]),
    .B(b[4]),
    .Y(_15_)
  );
  XNOR2x2_ASAP7_75t_L _42_ (
    .A(_15_),
    .B(_03_),
    .Y(s[4])
  );
  XNOR2x2_ASAP7_75t_L _43_ (
    .A(a[1]),
    .B(b[1]),
    .Y(_16_)
  );
  XNOR2x2_ASAP7_75t_L _44_ (
    .A(_16_),
    .B(_00_),
    .Y(s[1])
  );
  XNOR2x2_ASAP7_75t_L _45_ (
    .A(a[2]),
    .B(b[2]),
    .Y(_17_)
  );
  XNOR2x2_ASAP7_75t_L _46_ (
    .A(_17_),
    .B(_01_),
    .Y(s[2])
  );
endmodule
