/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module adder(a, b, s, cout);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  input [9:0] a;
  wire [9:0] a;
  input [9:0] b;
  wire [9:0] b;
  output cout;
  wire cout;
  output [9:0] s;
  wire [9:0] s;
  INVxp33_ASAP7_75t_L _27_ (
    .A(b[9]),
    .Y(_00_)
  );
  INVxp33_ASAP7_75t_L _28_ (
    .A(a[9]),
    .Y(_01_)
  );
  INVxp33_ASAP7_75t_L _29_ (
    .A(b[7]),
    .Y(_02_)
  );
  INVxp33_ASAP7_75t_L _30_ (
    .A(a[7]),
    .Y(_03_)
  );
  INVxp33_ASAP7_75t_L _31_ (
    .A(b[5]),
    .Y(_04_)
  );
  INVxp33_ASAP7_75t_L _32_ (
    .A(a[5]),
    .Y(_05_)
  );
  INVxp33_ASAP7_75t_L _33_ (
    .A(b[3]),
    .Y(_06_)
  );
  INVxp33_ASAP7_75t_L _34_ (
    .A(a[3]),
    .Y(_07_)
  );
  AND2x2_ASAP7_75t_L _35_ (
    .A(b[0]),
    .B(a[0]),
    .Y(_08_)
  );
  MAJx2_ASAP7_75t_L _36_ (
    .A(b[1]),
    .B(a[1]),
    .C(_08_),
    .Y(_09_)
  );
  MAJIxp5_ASAP7_75t_L _37_ (
    .A(b[2]),
    .B(a[2]),
    .C(_09_),
    .Y(_10_)
  );
  MAJIxp5_ASAP7_75t_L _38_ (
    .A(_06_),
    .B(_07_),
    .C(_10_),
    .Y(_11_)
  );
  MAJIxp5_ASAP7_75t_L _39_ (
    .A(b[4]),
    .B(a[4]),
    .C(_11_),
    .Y(_12_)
  );
  MAJIxp5_ASAP7_75t_L _40_ (
    .A(_04_),
    .B(_05_),
    .C(_12_),
    .Y(_13_)
  );
  MAJIxp5_ASAP7_75t_L _41_ (
    .A(b[6]),
    .B(a[6]),
    .C(_13_),
    .Y(_14_)
  );
  MAJIxp5_ASAP7_75t_L _42_ (
    .A(_02_),
    .B(_03_),
    .C(_14_),
    .Y(_15_)
  );
  MAJIxp5_ASAP7_75t_L _43_ (
    .A(b[8]),
    .B(a[8]),
    .C(_15_),
    .Y(_16_)
  );
  MAJIxp5_ASAP7_75t_L _44_ (
    .A(_00_),
    .B(_01_),
    .C(_16_),
    .Y(cout)
  );
  XNOR2xp5_ASAP7_75t_L _45_ (
    .A(b[1]),
    .B(a[1]),
    .Y(_17_)
  );
  XNOR2xp5_ASAP7_75t_L _46_ (
    .A(_08_),
    .B(_17_),
    .Y(s[1])
  );
  XNOR2xp5_ASAP7_75t_L _47_ (
    .A(b[2]),
    .B(a[2]),
    .Y(_18_)
  );
  XNOR2xp5_ASAP7_75t_L _48_ (
    .A(_09_),
    .B(_18_),
    .Y(s[2])
  );
  XOR2xp5_ASAP7_75t_L _49_ (
    .A(b[7]),
    .B(a[7]),
    .Y(_19_)
  );
  XNOR2xp5_ASAP7_75t_L _50_ (
    .A(_14_),
    .B(_19_),
    .Y(s[7])
  );
  NOR2xp33_ASAP7_75t_L _51_ (
    .A(b[0]),
    .B(a[0]),
    .Y(_20_)
  );
  NOR2xp33_ASAP7_75t_L _52_ (
    .A(_08_),
    .B(_20_),
    .Y(s[0])
  );
  XNOR2xp5_ASAP7_75t_L _53_ (
    .A(b[4]),
    .B(a[4]),
    .Y(_21_)
  );
  XNOR2xp5_ASAP7_75t_L _54_ (
    .A(_11_),
    .B(_21_),
    .Y(s[4])
  );
  XNOR2xp5_ASAP7_75t_L _55_ (
    .A(b[6]),
    .B(a[6]),
    .Y(_22_)
  );
  XNOR2xp5_ASAP7_75t_L _56_ (
    .A(_13_),
    .B(_22_),
    .Y(s[6])
  );
  XOR2xp5_ASAP7_75t_L _57_ (
    .A(b[9]),
    .B(a[9]),
    .Y(_23_)
  );
  XNOR2xp5_ASAP7_75t_L _58_ (
    .A(_16_),
    .B(_23_),
    .Y(s[9])
  );
  XOR2xp5_ASAP7_75t_L _59_ (
    .A(b[5]),
    .B(a[5]),
    .Y(_24_)
  );
  XNOR2xp5_ASAP7_75t_L _60_ (
    .A(_12_),
    .B(_24_),
    .Y(s[5])
  );
  XOR2xp5_ASAP7_75t_L _61_ (
    .A(b[3]),
    .B(a[3]),
    .Y(_25_)
  );
  XNOR2xp5_ASAP7_75t_L _62_ (
    .A(_10_),
    .B(_25_),
    .Y(s[3])
  );
  XNOR2xp5_ASAP7_75t_L _63_ (
    .A(b[8]),
    .B(a[8]),
    .Y(_26_)
  );
  XNOR2xp5_ASAP7_75t_L _64_ (
    .A(_15_),
    .B(_26_),
    .Y(s[8])
  );
endmodule
