/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module adder(a, b, sum, cout);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  input [4:0] a;
  wire [4:0] a;
  input [4:0] b;
  wire [4:0] b;
  output cout;
  wire cout;
  output [4:0] sum;
  wire [4:0] sum;
  AND2x2_ASAP7_75t_L _08_ (
    .A(b[0]),
    .B(a[0]),
    .Y(_00_)
  );
  MAJx2_ASAP7_75t_L _09_ (
    .A(b[1]),
    .B(a[1]),
    .C(_00_),
    .Y(_01_)
  );
  MAJx2_ASAP7_75t_L _10_ (
    .A(b[2]),
    .B(a[2]),
    .C(_01_),
    .Y(_02_)
  );
  MAJx2_ASAP7_75t_L _11_ (
    .A(b[3]),
    .B(a[3]),
    .C(_02_),
    .Y(_03_)
  );
  MAJx2_ASAP7_75t_L _12_ (
    .A(b[4]),
    .B(a[4]),
    .C(_03_),
    .Y(cout)
  );
  XOR2xp5_ASAP7_75t_L _13_ (
    .A(b[0]),
    .B(a[0]),
    .Y(sum[0])
  );
  XNOR2xp5_ASAP7_75t_L _14_ (
    .A(b[1]),
    .B(a[1]),
    .Y(_04_)
  );
  XNOR2xp5_ASAP7_75t_L _15_ (
    .A(_04_),
    .B(_00_),
    .Y(sum[1])
  );
  XNOR2xp5_ASAP7_75t_L _16_ (
    .A(b[4]),
    .B(a[4]),
    .Y(_05_)
  );
  XNOR2xp5_ASAP7_75t_L _17_ (
    .A(_05_),
    .B(_03_),
    .Y(sum[4])
  );
  XNOR2xp5_ASAP7_75t_L _18_ (
    .A(b[3]),
    .B(a[3]),
    .Y(_06_)
  );
  XNOR2xp5_ASAP7_75t_L _19_ (
    .A(_06_),
    .B(_02_),
    .Y(sum[3])
  );
  XNOR2xp5_ASAP7_75t_L _20_ (
    .A(b[2]),
    .B(a[2]),
    .Y(_07_)
  );
  XNOR2xp5_ASAP7_75t_L _21_ (
    .A(_07_),
    .B(_01_),
    .Y(sum[2])
  );
endmodule
