/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module adder(a, b, sum, cout);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  input [4:0] a;
  wire [4:0] a;
  input [4:0] b;
  wire [4:0] b;
  output cout;
  wire cout;
  wire in0;
  wire in1;
  wire in2;
  wire in3;
  wire in4;
  wire in5;
  wire in6;
  wire in7;
  wire in8;
  wire in9;
  wire out0;
  wire out1;
  wire out2;
  wire out3;
  wire out4;
  wire out5;
  output [4:0] sum;
  wire [4:0] sum;
  wire var20;
  wire var21;
  wire var22;
  wire var23;
  wire var24;
  wire var5;
  \$_XOR_  _19_ (
    .A(a[4]),
    .B(b[4]),
    .Y(_00_)
  );
  \$_NAND_  _20_ (
    .A(a[3]),
    .B(b[3]),
    .Y(_01_)
  );
  \$_XOR_  _21_ (
    .A(a[3]),
    .B(b[3]),
    .Y(_02_)
  );
  \$_NAND_  _22_ (
    .A(a[2]),
    .B(b[2]),
    .Y(_03_)
  );
  \$_ANDNOT_  _23_ (
    .A(_02_),
    .B(_03_),
    .Y(_04_)
  );
  \$_ANDNOT_  _24_ (
    .A(_01_),
    .B(_04_),
    .Y(_05_)
  );
  \$_XNOR_  _25_ (
    .A(a[2]),
    .B(b[2]),
    .Y(_06_)
  );
  \$_ANDNOT_  _26_ (
    .A(_02_),
    .B(_06_),
    .Y(_07_)
  );
  \$_NAND_  _27_ (
    .A(a[1]),
    .B(b[1]),
    .Y(_08_)
  );
  \$_XOR_  _28_ (
    .A(a[1]),
    .B(b[1]),
    .Y(_09_)
  );
  \$_NAND_  _29_ (
    .A(a[0]),
    .B(b[0]),
    .Y(_10_)
  );
  \$_ANDNOT_  _30_ (
    .A(_09_),
    .B(_10_),
    .Y(_11_)
  );
  \$_ANDNOT_  _31_ (
    .A(_08_),
    .B(_11_),
    .Y(_12_)
  );
  \$_ANDNOT_  _32_ (
    .A(_07_),
    .B(_12_),
    .Y(_13_)
  );
  \$_ANDNOT_  _33_ (
    .A(_05_),
    .B(_13_),
    .Y(_14_)
  );
  \$_XNOR_  _34_ (
    .A(_14_),
    .B(_00_),
    .Y(out1)
  );
  \$_AND_  _35_ (
    .A(a[4]),
    .B(b[4]),
    .Y(_15_)
  );
  \$_ANDNOT_  _36_ (
    .A(_00_),
    .B(_14_),
    .Y(_16_)
  );
  \$_OR_  _37_ (
    .A(_16_),
    .B(_15_),
    .Y(cout)
  );
  \$_XOR_  _38_ (
    .A(a[0]),
    .B(b[0]),
    .Y(out5)
  );
  \$_XOR_  _39_ (
    .A(_12_),
    .B(_06_),
    .Y(out3)
  );
  \$_NOR_  _40_ (
    .A(_12_),
    .B(_06_),
    .Y(_17_)
  );
  \$_ORNOT_  _41_ (
    .A(_17_),
    .B(_03_),
    .Y(_18_)
  );
  \$_XOR_  _42_ (
    .A(_18_),
    .B(_02_),
    .Y(out2)
  );
  \$_XNOR_  _43_ (
    .A(_10_),
    .B(_09_),
    .Y(out4)
  );
  assign in0 = a[4];
  assign in1 = a[3];
  assign in2 = a[2];
  assign in3 = a[1];
  assign in4 = a[0];
  assign in5 = b[4];
  assign in6 = b[3];
  assign in7 = b[2];
  assign in8 = b[1];
  assign in9 = b[0];
  assign out0 = cout;
  assign sum = { out1, out2, out3, out4, out5 };
  assign var20 = cout;
  assign var21 = out4;
  assign var22 = out3;
  assign var23 = out2;
  assign var24 = out1;
  assign var5 = out5;
endmodule
