/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module adder(a, b, sum, cout);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  input [4:0] a;
  wire [4:0] a;
  input [4:0] b;
  wire [4:0] b;
  output cout;
  wire cout;
  wire in0;
  wire in1;
  wire in2;
  wire in3;
  wire in4;
  wire in5;
  wire in6;
  wire in7;
  wire in8;
  wire in9;
  wire out0;
  wire out1;
  wire out2;
  wire out3;
  wire out4;
  wire out5;
  output [4:0] sum;
  wire [4:0] sum;
  wire var29;
  wire var30;
  wire var31;
  wire var32;
  wire var33;
  wire var5;
  \$_XOR_  _29_ (
    .A(a[1]),
    .B(b[1]),
    .Y(_00_)
  );
  \$_AND_  _30_ (
    .A(a[0]),
    .B(b[0]),
    .Y(_01_)
  );
  \$_XOR_  _31_ (
    .A(_01_),
    .B(_00_),
    .Y(out4)
  );
  \$_AND_  _32_ (
    .A(a[4]),
    .B(b[4]),
    .Y(_02_)
  );
  \$_XNOR_  _33_ (
    .A(a[4]),
    .B(b[4]),
    .Y(_03_)
  );
  \$_NAND_  _34_ (
    .A(a[3]),
    .B(b[3]),
    .Y(_04_)
  );
  \$_NOR_  _35_ (
    .A(_04_),
    .B(_03_),
    .Y(_05_)
  );
  \$_OR_  _36_ (
    .A(_05_),
    .B(_02_),
    .Y(_06_)
  );
  \$_XNOR_  _37_ (
    .A(a[3]),
    .B(b[3]),
    .Y(_07_)
  );
  \$_OR_  _38_ (
    .A(_07_),
    .B(_03_),
    .Y(_08_)
  );
  \$_NAND_  _39_ (
    .A(a[2]),
    .B(b[2]),
    .Y(_09_)
  );
  \$_XNOR_  _40_ (
    .A(a[2]),
    .B(b[2]),
    .Y(_10_)
  );
  \$_NAND_  _41_ (
    .A(a[1]),
    .B(b[1]),
    .Y(_11_)
  );
  \$_NOR_  _42_ (
    .A(_11_),
    .B(_10_),
    .Y(_12_)
  );
  \$_ANDNOT_  _43_ (
    .A(_09_),
    .B(_12_),
    .Y(_13_)
  );
  \$_NOR_  _44_ (
    .A(_13_),
    .B(_08_),
    .Y(_14_)
  );
  \$_OR_  _45_ (
    .A(_14_),
    .B(_06_),
    .Y(_15_)
  );
  \$_ORNOT_  _46_ (
    .A(_10_),
    .B(_00_),
    .Y(_16_)
  );
  \$_OR_  _47_ (
    .A(_16_),
    .B(_08_),
    .Y(_17_)
  );
  \$_ANDNOT_  _48_ (
    .A(_01_),
    .B(_17_),
    .Y(_18_)
  );
  \$_OR_  _49_ (
    .A(_18_),
    .B(_15_),
    .Y(cout)
  );
  \$_ANDNOT_  _50_ (
    .A(_01_),
    .B(_16_),
    .Y(_19_)
  );
  \$_ANDNOT_  _51_ (
    .A(_13_),
    .B(_19_),
    .Y(_20_)
  );
  \$_XOR_  _52_ (
    .A(_20_),
    .B(_07_),
    .Y(out2)
  );
  \$_XOR_  _53_ (
    .A(a[0]),
    .B(b[0]),
    .Y(out5)
  );
  \$_XOR_  _54_ (
    .A(a[3]),
    .B(b[3]),
    .Y(_21_)
  );
  \$_ANDNOT_  _55_ (
    .A(_21_),
    .B(_09_),
    .Y(_22_)
  );
  \$_ANDNOT_  _56_ (
    .A(_04_),
    .B(_22_),
    .Y(_23_)
  );
  \$_ANDNOT_  _57_ (
    .A(_21_),
    .B(_10_),
    .Y(_24_)
  );
  \$_AND_  _58_ (
    .A(_01_),
    .B(_00_),
    .Y(_25_)
  );
  \$_ANDNOT_  _59_ (
    .A(_11_),
    .B(_25_),
    .Y(_26_)
  );
  \$_ANDNOT_  _60_ (
    .A(_24_),
    .B(_26_),
    .Y(_27_)
  );
  \$_ANDNOT_  _61_ (
    .A(_23_),
    .B(_27_),
    .Y(_28_)
  );
  \$_XOR_  _62_ (
    .A(_28_),
    .B(_03_),
    .Y(out1)
  );
  \$_XOR_  _63_ (
    .A(_26_),
    .B(_10_),
    .Y(out3)
  );
  assign in0 = a[4];
  assign in1 = a[3];
  assign in2 = a[2];
  assign in3 = a[1];
  assign in4 = a[0];
  assign in5 = b[4];
  assign in6 = b[3];
  assign in7 = b[2];
  assign in8 = b[1];
  assign in9 = b[0];
  assign out0 = cout;
  assign sum = { out1, out2, out3, out4, out5 };
  assign var29 = cout;
  assign var30 = out4;
  assign var31 = out3;
  assign var32 = out2;
  assign var33 = out1;
  assign var5 = out5;
endmodule
