/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module adder(a, b, sum, cout);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  input [4:0] a;
  wire [4:0] a;
  input [4:0] b;
  wire [4:0] b;
  output cout;
  wire cout;
  output [4:0] sum;
  wire [4:0] sum;
  AND2x2_ASAP7_75t_L _13_ (
    .A(a[0]),
    .B(b[0]),
    .Y(_00_)
  );
  XNOR2xp5_ASAP7_75t_L _14_ (
    .A(a[1]),
    .B(b[1]),
    .Y(_01_)
  );
  XNOR2xp5_ASAP7_75t_L _15_ (
    .A(_00_),
    .B(_01_),
    .Y(sum[1])
  );
  MAJIxp5_ASAP7_75t_L _16_ (
    .A(a[1]),
    .B(b[1]),
    .C(_00_),
    .Y(_02_)
  );
  XOR2xp5_ASAP7_75t_L _17_ (
    .A(a[2]),
    .B(b[2]),
    .Y(_03_)
  );
  XNOR2xp5_ASAP7_75t_L _18_ (
    .A(_02_),
    .B(_03_),
    .Y(sum[2])
  );
  NOR2xp33_ASAP7_75t_L _19_ (
    .A(a[0]),
    .B(b[0]),
    .Y(_04_)
  );
  NOR2xp33_ASAP7_75t_L _20_ (
    .A(_00_),
    .B(_04_),
    .Y(sum[0])
  );
  INVxp33_ASAP7_75t_L _21_ (
    .A(a[4]),
    .Y(_05_)
  );
  INVxp33_ASAP7_75t_L _22_ (
    .A(b[4]),
    .Y(_06_)
  );
  INVxp33_ASAP7_75t_L _23_ (
    .A(a[2]),
    .Y(_07_)
  );
  INVxp33_ASAP7_75t_L _24_ (
    .A(b[2]),
    .Y(_08_)
  );
  MAJIxp5_ASAP7_75t_L _25_ (
    .A(_07_),
    .B(_08_),
    .C(_02_),
    .Y(_09_)
  );
  MAJIxp5_ASAP7_75t_L _26_ (
    .A(a[3]),
    .B(b[3]),
    .C(_09_),
    .Y(_10_)
  );
  MAJIxp5_ASAP7_75t_L _27_ (
    .A(_05_),
    .B(_06_),
    .C(_10_),
    .Y(cout)
  );
  XNOR2xp5_ASAP7_75t_L _28_ (
    .A(a[3]),
    .B(b[3]),
    .Y(_11_)
  );
  XNOR2xp5_ASAP7_75t_L _29_ (
    .A(_09_),
    .B(_11_),
    .Y(sum[3])
  );
  XOR2xp5_ASAP7_75t_L _30_ (
    .A(a[4]),
    .B(b[4]),
    .Y(_12_)
  );
  XNOR2xp5_ASAP7_75t_L _31_ (
    .A(_10_),
    .B(_12_),
    .Y(sum[4])
  );
endmodule
