/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module adder(a, b, sum, cout);
  input [4:0] a;
  wire [4:0] a;
  input [4:0] b;
  wire [4:0] b;
  output cout;
  wire cout;
  wire in0;
  wire in1;
  wire in2;
  wire in3;
  wire in4;
  wire in5;
  wire in6;
  wire in7;
  wire in8;
  wire in9;
  wire out0;
  wire out1;
  wire out2;
  wire out3;
  wire out4;
  wire out5;
  output [4:0] sum;
  wire [4:0] sum;
  wire var0;
  wire var1;
  wire var10;
  wire var11;
  wire var12;
  wire var13;
  wire var14;
  wire var15;
  wire var16;
  wire var17;
  wire var18;
  wire var19;
  wire var2;
  wire var20;
  wire var22;
  wire var23;
  wire var24;
  wire var25;
  wire var3;
  wire var4;
  wire var5;
  wire var6;
  wire var7;
  wire var8;
  wire var9;
  \$_XOR_  _00_ (
    .A(var9),
    .B(var16),
    .Y(out1)
  );
  \$_AND_  _01_ (
    .A(b[3]),
    .B(a[3]),
    .Y(var3)
  );
  \$_XOR_  _02_ (
    .A(b[2]),
    .B(a[2]),
    .Y(var7)
  );
  \$_XOR_  _03_ (
    .A(b[1]),
    .B(a[1]),
    .Y(var6)
  );
  \$_AND_  _04_ (
    .A(var8),
    .B(var7),
    .Y(var12)
  );
  \$_AND_  _05_ (
    .A(var6),
    .B(var0),
    .Y(var13)
  );
  \$_XOR_  _06_ (
    .A(b[0]),
    .B(a[0]),
    .Y(out5)
  );
  \$_AND_  _07_ (
    .A(var8),
    .B(var2),
    .Y(var10)
  );
  \$_XOR_  _08_ (
    .A(var7),
    .B(var14),
    .Y(out3)
  );
  \$_XOR_  _09_ (
    .A(b[3]),
    .B(a[3]),
    .Y(var8)
  );
  \$_AND_  _10_ (
    .A(b[0]),
    .B(a[0]),
    .Y(var0)
  );
  \$_XOR_  _11_ (
    .A(var6),
    .B(var0),
    .Y(out4)
  );
  \$_OR_  _12_ (
    .A(var3),
    .B(var10),
    .Y(var11)
  );
  \$_XOR_  _13_ (
    .A(b[4]),
    .B(a[4]),
    .Y(var9)
  );
  \$_AND_  _14_ (
    .A(b[4]),
    .B(a[4]),
    .Y(var4)
  );
  \$_AND_  _15_ (
    .A(b[2]),
    .B(a[2]),
    .Y(var2)
  );
  \$_OR_  _16_ (
    .A(var2),
    .B(var19),
    .Y(var20)
  );
  \$_OR_  _17_ (
    .A(var1),
    .B(var13),
    .Y(var14)
  );
  \$_AND_  _18_ (
    .A(var7),
    .B(var14),
    .Y(var19)
  );
  \$_OR_  _19_ (
    .A(var4),
    .B(var17),
    .Y(cout)
  );
  \$_AND_  _20_ (
    .A(b[1]),
    .B(a[1]),
    .Y(var1)
  );
  \$_AND_  _21_ (
    .A(var9),
    .B(var16),
    .Y(var17)
  );
  \$_OR_  _22_ (
    .A(var11),
    .B(var15),
    .Y(var16)
  );
  \$_AND_  _23_ (
    .A(var12),
    .B(var14),
    .Y(var15)
  );
  \$_XOR_  _24_ (
    .A(var8),
    .B(var20),
    .Y(out2)
  );
  assign in0 = a[4];
  assign in1 = a[3];
  assign in2 = a[2];
  assign in3 = a[1];
  assign in4 = a[0];
  assign in5 = b[4];
  assign in6 = b[3];
  assign in7 = b[2];
  assign in8 = b[1];
  assign in9 = b[0];
  assign out0 = cout;
  assign sum = { out1, out2, out3, out4, out5 };
  assign var18 = cout;
  assign var22 = out4;
  assign var23 = out3;
  assign var24 = out2;
  assign var25 = out1;
  assign var5 = out5;
endmodule
