/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module adder(a, b, sum, cout);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  input [4:0] a;
  wire [4:0] a;
  input [4:0] b;
  wire [4:0] b;
  output cout;
  wire cout;
  output [4:0] sum;
  wire [4:0] sum;
  AND2x2_ASAP7_75t_L _19_ (
    .A(a[0]),
    .B(b[0]),
    .Y(_00_)
  );
  NOR2xp33_ASAP7_75t_L _20_ (
    .A(a[1]),
    .B(b[1]),
    .Y(_01_)
  );
  AND2x2_ASAP7_75t_L _21_ (
    .A(a[1]),
    .B(b[1]),
    .Y(_02_)
  );
  NOR2xp33_ASAP7_75t_L _22_ (
    .A(_01_),
    .B(_02_),
    .Y(_03_)
  );
  XOR2xp5_ASAP7_75t_L _23_ (
    .A(_00_),
    .B(_03_),
    .Y(sum[1])
  );
  MAJIxp5_ASAP7_75t_L _24_ (
    .A(a[1]),
    .B(b[1]),
    .C(_00_),
    .Y(_04_)
  );
  XOR2xp5_ASAP7_75t_L _25_ (
    .A(a[2]),
    .B(b[2]),
    .Y(_05_)
  );
  XNOR2xp5_ASAP7_75t_L _26_ (
    .A(_04_),
    .B(_05_),
    .Y(sum[2])
  );
  XOR2xp5_ASAP7_75t_L _27_ (
    .A(a[0]),
    .B(b[0]),
    .Y(sum[0])
  );
  XOR2xp5_ASAP7_75t_L _28_ (
    .A(a[4]),
    .B(b[4]),
    .Y(_06_)
  );
  XNOR2xp5_ASAP7_75t_L _29_ (
    .A(a[3]),
    .B(b[3]),
    .Y(_07_)
  );
  INVxp33_ASAP7_75t_L _30_ (
    .A(_07_),
    .Y(_08_)
  );
  AND2x2_ASAP7_75t_L _31_ (
    .A(a[3]),
    .B(b[3]),
    .Y(_09_)
  );
  AND3x1_ASAP7_75t_L _32_ (
    .A(a[2]),
    .B(b[2]),
    .C(_08_),
    .Y(_10_)
  );
  INVxp33_ASAP7_75t_L _33_ (
    .A(_05_),
    .Y(_11_)
  );
  NOR3xp33_ASAP7_75t_L _34_ (
    .A(_04_),
    .B(_11_),
    .C(_07_),
    .Y(_12_)
  );
  OR3x1_ASAP7_75t_L _35_ (
    .A(_09_),
    .B(_10_),
    .C(_12_),
    .Y(_13_)
  );
  NAND3xp33_ASAP7_75t_L _36_ (
    .A(_06_),
    .B(_08_),
    .C(_13_),
    .Y(_14_)
  );
  MAJIxp5_ASAP7_75t_L _37_ (
    .A(a[4]),
    .B(b[4]),
    .C(_09_),
    .Y(_15_)
  );
  NAND2xp33_ASAP7_75t_L _38_ (
    .A(_14_),
    .B(_15_),
    .Y(cout)
  );
  XOR2xp5_ASAP7_75t_L _39_ (
    .A(_06_),
    .B(_13_),
    .Y(sum[4])
  );
  MAJIxp5_ASAP7_75t_L _40_ (
    .A(a[2]),
    .B(b[2]),
    .C(_02_),
    .Y(_16_)
  );
  NAND3xp33_ASAP7_75t_L _41_ (
    .A(_00_),
    .B(_03_),
    .C(_05_),
    .Y(_17_)
  );
  NAND2xp33_ASAP7_75t_L _42_ (
    .A(_16_),
    .B(_17_),
    .Y(_18_)
  );
  XNOR2xp5_ASAP7_75t_L _43_ (
    .A(_07_),
    .B(_18_),
    .Y(sum[3])
  );
endmodule
