/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module adder(a, b, s, cout);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  input [7:0] a;
  wire [7:0] a;
  input [7:0] b;
  wire [7:0] b;
  output cout;
  wire cout;
  output [7:0] s;
  wire [7:0] s;
  XOR2xp5_ASAP7_75t_L _14_ (
    .A(b[0]),
    .B(a[0]),
    .Y(s[0])
  );
  AND2x2_ASAP7_75t_L _15_ (
    .A(b[0]),
    .B(a[0]),
    .Y(_00_)
  );
  MAJx2_ASAP7_75t_L _16_ (
    .A(b[1]),
    .B(a[1]),
    .C(_00_),
    .Y(_01_)
  );
  XNOR2xp5_ASAP7_75t_L _17_ (
    .A(b[2]),
    .B(a[2]),
    .Y(_02_)
  );
  XNOR2xp5_ASAP7_75t_L _18_ (
    .A(_01_),
    .B(_02_),
    .Y(s[2])
  );
  XNOR2xp5_ASAP7_75t_L _19_ (
    .A(b[1]),
    .B(a[1]),
    .Y(_03_)
  );
  XNOR2xp5_ASAP7_75t_L _20_ (
    .A(_03_),
    .B(_00_),
    .Y(s[1])
  );
  MAJx2_ASAP7_75t_L _21_ (
    .A(b[2]),
    .B(a[2]),
    .C(_01_),
    .Y(_04_)
  );
  MAJx2_ASAP7_75t_L _22_ (
    .A(b[3]),
    .B(a[3]),
    .C(_04_),
    .Y(_05_)
  );
  MAJx2_ASAP7_75t_L _23_ (
    .A(b[4]),
    .B(a[4]),
    .C(_05_),
    .Y(_06_)
  );
  MAJx2_ASAP7_75t_L _24_ (
    .A(b[5]),
    .B(a[5]),
    .C(_06_),
    .Y(_07_)
  );
  XNOR2xp5_ASAP7_75t_L _25_ (
    .A(b[6]),
    .B(a[6]),
    .Y(_08_)
  );
  XNOR2xp5_ASAP7_75t_L _26_ (
    .A(_07_),
    .B(_08_),
    .Y(s[6])
  );
  XNOR2xp5_ASAP7_75t_L _27_ (
    .A(b[3]),
    .B(a[3]),
    .Y(_09_)
  );
  XNOR2xp5_ASAP7_75t_L _28_ (
    .A(_09_),
    .B(_04_),
    .Y(s[3])
  );
  MAJx2_ASAP7_75t_L _29_ (
    .A(b[6]),
    .B(a[6]),
    .C(_07_),
    .Y(_10_)
  );
  MAJx2_ASAP7_75t_L _30_ (
    .A(b[7]),
    .B(a[7]),
    .C(_10_),
    .Y(cout)
  );
  XNOR2xp5_ASAP7_75t_L _31_ (
    .A(b[7]),
    .B(a[7]),
    .Y(_11_)
  );
  XNOR2xp5_ASAP7_75t_L _32_ (
    .A(_10_),
    .B(_11_),
    .Y(s[7])
  );
  XNOR2xp5_ASAP7_75t_L _33_ (
    .A(b[5]),
    .B(a[5]),
    .Y(_12_)
  );
  XNOR2xp5_ASAP7_75t_L _34_ (
    .A(_06_),
    .B(_12_),
    .Y(s[5])
  );
  XNOR2xp5_ASAP7_75t_L _35_ (
    .A(b[4]),
    .B(a[4]),
    .Y(_13_)
  );
  XNOR2xp5_ASAP7_75t_L _36_ (
    .A(_05_),
    .B(_13_),
    .Y(s[4])
  );
endmodule
