/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module adder(a, b, s, cout);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  input [7:0] a;
  wire [7:0] a;
  input [7:0] b;
  wire [7:0] b;
  wire c_0;
  wire c_1;
  wire c_2;
  wire c_3;
  wire c_4;
  wire c_5;
  wire c_6;
  wire c_7;
  wire c_8;
  output cout;
  wire cout;
  wire g_0;
  wire g_1;
  wire g_10;
  wire g_11;
  wire g_12;
  wire g_13;
  wire g_14;
  wire g_2;
  wire g_3;
  wire g_4;
  wire g_5;
  wire g_6;
  wire g_7;
  wire g_8;
  wire g_9;
  wire p_0;
  wire p_1;
  wire p_2;
  wire p_3;
  wire p_4;
  wire p_5;
  wire p_6;
  wire p_7;
  output [7:0] s;
  wire [7:0] s;
  \$_XOR_  _07_ (
    .A(p_4),
    .B(c_4),
    .Y(s[4])
  );
  \$_XOR_  _08_ (
    .A(a[6]),
    .B(b[6]),
    .Y(p_6)
  );
  \$_AND_  _09_ (
    .A(p_7),
    .B(c_7),
    .Y(_06_)
  );
  \$_OR_  _10_ (
    .A(g_4),
    .B(_03_),
    .Y(c_5)
  );
  \$_AND_  _11_ (
    .A(a[5]),
    .B(b[5]),
    .Y(g_5)
  );
  \$_XOR_  _12_ (
    .A(p_7),
    .B(c_7),
    .Y(s[7])
  );
  \$_XOR_  _13_ (
    .A(a[3]),
    .B(b[3]),
    .Y(p_3)
  );
  \$_XOR_  _14_ (
    .A(p_3),
    .B(c_3),
    .Y(s[3])
  );
  \$_XOR_  _15_ (
    .A(p_1),
    .B(c_1),
    .Y(s[1])
  );
  \$_AND_  _16_ (
    .A(p_5),
    .B(c_5),
    .Y(_04_)
  );
  \$_AND_  _17_ (
    .A(a[4]),
    .B(b[4]),
    .Y(g_4)
  );
  \$_AND_  _18_ (
    .A(p_4),
    .B(c_4),
    .Y(_03_)
  );
  \$_OR_  _19_ (
    .A(g_7),
    .B(_06_),
    .Y(cout)
  );
  \$_AND_  _20_ (
    .A(a[0]),
    .B(b[0]),
    .Y(c_1)
  );
  \$_AND_  _21_ (
    .A(a[2]),
    .B(b[2]),
    .Y(g_2)
  );
  \$_OR_  _22_ (
    .A(g_3),
    .B(_02_),
    .Y(c_4)
  );
  \$_XOR_  _23_ (
    .A(a[1]),
    .B(b[1]),
    .Y(p_1)
  );
  \$_XOR_  _24_ (
    .A(a[5]),
    .B(b[5]),
    .Y(p_5)
  );
  \$_AND_  _25_ (
    .A(p_3),
    .B(c_3),
    .Y(_02_)
  );
  \$_AND_  _26_ (
    .A(a[1]),
    .B(b[1]),
    .Y(g_1)
  );
  \$_XOR_  _27_ (
    .A(p_5),
    .B(c_5),
    .Y(s[5])
  );
  \$_XOR_  _28_ (
    .A(p_2),
    .B(c_2),
    .Y(s[2])
  );
  \$_XOR_  _29_ (
    .A(a[0]),
    .B(b[0]),
    .Y(p_0)
  );
  \$_OR_  _30_ (
    .A(g_2),
    .B(_01_),
    .Y(c_3)
  );
  \$_XOR_  _31_ (
    .A(a[2]),
    .B(b[2]),
    .Y(p_2)
  );
  \$_XOR_  _32_ (
    .A(p_6),
    .B(c_6),
    .Y(s[6])
  );
  \$_AND_  _33_ (
    .A(p_2),
    .B(c_2),
    .Y(_01_)
  );
  \$_AND_  _34_ (
    .A(a[6]),
    .B(b[6]),
    .Y(g_6)
  );
  \$_OR_  _35_ (
    .A(g_1),
    .B(_00_),
    .Y(c_2)
  );
  \$_OR_  _36_ (
    .A(g_5),
    .B(_04_),
    .Y(c_6)
  );
  \$_AND_  _37_ (
    .A(p_1),
    .B(c_1),
    .Y(_00_)
  );
  \$_AND_  _38_ (
    .A(a[3]),
    .B(b[3]),
    .Y(g_3)
  );
  \$_AND_  _39_ (
    .A(a[7]),
    .B(b[7]),
    .Y(g_7)
  );
  \$_AND_  _40_ (
    .A(p_6),
    .B(c_6),
    .Y(_05_)
  );
  \$_XOR_  _41_ (
    .A(a[4]),
    .B(b[4]),
    .Y(p_4)
  );
  \$_OR_  _42_ (
    .A(g_6),
    .B(_05_),
    .Y(c_7)
  );
  \$_XOR_  _43_ (
    .A(a[7]),
    .B(b[7]),
    .Y(p_7)
  );
  assign c_0 = 1'h0;
  assign c_8 = cout;
  assign g_0 = c_1;
  assign g_10 = c_4;
  assign g_11 = c_5;
  assign g_12 = c_6;
  assign g_13 = c_7;
  assign g_14 = cout;
  assign g_8 = c_2;
  assign g_9 = c_3;
  assign s[0] = p_0;
endmodule
