/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module adder(a, b, s, cout);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  input [5:0] a;
  wire [5:0] a;
  input [5:0] b;
  wire [5:0] b;
  wire c_0;
  wire c_1;
  wire c_2;
  wire c_3;
  wire c_4;
  wire c_5;
  wire c_6;
  output cout;
  wire cout;
  wire g_0;
  wire g_1;
  wire g_10;
  wire g_2;
  wire g_3;
  wire g_4;
  wire g_5;
  wire g_6;
  wire g_7;
  wire g_8;
  wire g_9;
  wire p_0;
  wire p_1;
  wire p_2;
  wire p_3;
  wire p_4;
  wire p_5;
  output [5:0] s;
  wire [5:0] s;
  \$_AND_  _05_ (
    .A(a[0]),
    .B(b[0]),
    .Y(c_1)
  );
  \$_OR_  _06_ (
    .A(g_4),
    .B(_03_),
    .Y(c_5)
  );
  \$_AND_  _07_ (
    .A(p_4),
    .B(c_4),
    .Y(_03_)
  );
  \$_AND_  _08_ (
    .A(a[5]),
    .B(b[5]),
    .Y(g_5)
  );
  \$_AND_  _09_ (
    .A(p_2),
    .B(c_2),
    .Y(_01_)
  );
  \$_AND_  _10_ (
    .A(a[3]),
    .B(b[3]),
    .Y(g_3)
  );
  \$_XOR_  _11_ (
    .A(a[0]),
    .B(b[0]),
    .Y(p_0)
  );
  \$_OR_  _12_ (
    .A(g_1),
    .B(_00_),
    .Y(c_2)
  );
  \$_XOR_  _13_ (
    .A(a[2]),
    .B(b[2]),
    .Y(p_2)
  );
  \$_OR_  _14_ (
    .A(g_3),
    .B(_02_),
    .Y(c_4)
  );
  \$_AND_  _15_ (
    .A(a[1]),
    .B(b[1]),
    .Y(g_1)
  );
  \$_XOR_  _16_ (
    .A(a[3]),
    .B(b[3]),
    .Y(p_3)
  );
  \$_XOR_  _17_ (
    .A(p_5),
    .B(c_5),
    .Y(s[5])
  );
  \$_AND_  _18_ (
    .A(a[4]),
    .B(b[4]),
    .Y(g_4)
  );
  \$_AND_  _19_ (
    .A(p_1),
    .B(c_1),
    .Y(_00_)
  );
  \$_XOR_  _20_ (
    .A(p_3),
    .B(c_3),
    .Y(s[3])
  );
  \$_XOR_  _21_ (
    .A(a[1]),
    .B(b[1]),
    .Y(p_1)
  );
  \$_XOR_  _22_ (
    .A(a[4]),
    .B(b[4]),
    .Y(p_4)
  );
  \$_AND_  _23_ (
    .A(a[2]),
    .B(b[2]),
    .Y(g_2)
  );
  \$_XOR_  _24_ (
    .A(a[5]),
    .B(b[5]),
    .Y(p_5)
  );
  \$_XOR_  _25_ (
    .A(p_4),
    .B(c_4),
    .Y(s[4])
  );
  \$_XOR_  _26_ (
    .A(p_2),
    .B(c_2),
    .Y(s[2])
  );
  \$_AND_  _27_ (
    .A(p_3),
    .B(c_3),
    .Y(_02_)
  );
  \$_XOR_  _28_ (
    .A(p_1),
    .B(c_1),
    .Y(s[1])
  );
  \$_OR_  _29_ (
    .A(g_2),
    .B(_01_),
    .Y(c_3)
  );
  \$_AND_  _30_ (
    .A(p_5),
    .B(c_5),
    .Y(_04_)
  );
  \$_OR_  _31_ (
    .A(g_5),
    .B(_04_),
    .Y(cout)
  );
  assign c_0 = 1'h0;
  assign c_6 = cout;
  assign g_0 = c_1;
  assign g_10 = cout;
  assign g_6 = c_2;
  assign g_7 = c_3;
  assign g_8 = c_4;
  assign g_9 = c_5;
  assign s[0] = p_0;
endmodule
